version: '3.8'

services:
  web:
    mem_limit: 512m  # Limit memory usage to 512MB
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - app-network

  client:
    mem_limit: 2048m  # Limit memory usage to 2048MB
    image: nginx:latest  # Use the Nginx Docker image
    volumes:
      - ./client/build:/usr/share/nginx/html  # Mount client build directory
    ports:
      - "3000:80"  # Map port 80 of the container to port 3000 on the host
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
