version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # This assumes you have a custom nginx.conf file
    depends_on:
      - client
      - web
    networks:
      - app-network

  client:
    build: ./client  # Assuming you have a Dockerfile in the client directory
    networks:
      - app-network
    ports:
      - "80:80"  # Expose the client's port (optional if you want to expose client on host)

  web:
    image: recipe-app-docker-web  # Image name for your backend
    build: ./server  # Assuming you have a Dockerfile in the server directory
    networks:
      - app-network
    ports:
      - "5000:5000"  # Exposes port 5000 of the container to port 5000 of the host

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
